In [173]:
# Builing CNN for Image Classfier

In [ ]:
# Importing the Keras libraries and packages
from keras.models import Sequential     # making ANN and initialize
from keras.layers import Convolution2D  # ADDING CONCOLUTIONl layers
from keras.layers import MaxPooling2D   # adding pooling step  2d its for pcis and 3D is for movies 
from keras.layers import Flatten        # flt poolling into large vector
from keras.layers import Dense          # adding layers

In [174]:
Classifier=Sequential()

In [175]:
Classifier.add(Convolution2D(64,3,3,input_shape=(64,64,3), activation='relu'))

/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (3, 3), input_shape=(64, 64, 3..., activation="relu")`
  """Entry point for launching an IPython kernel.


In [176]:
Classifier.add(MaxPooling2D(pool_size=(2,2)))

In [177]:
# add another layer , this time i dont need input dims

Classifier.add(Convolution2D(64,3,3, activation='relu'))
Classifier.add(MaxPooling2D(pool_size=(2,2)))

/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:3: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (3, 3), activation="relu")`
  This is separate from the ipykernel package so we can avoid doing imports until


In [178]:

Classifier.add(Convolution2D(64,3,3, activation='relu'))
Classifier.add(MaxPooling2D(pool_size=(2,2)))

/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:2: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (3, 3), activation="relu")`
  


In [179]:

Classifier.add(Convolution2D(64,3,3, activation='relu'))
Classifier.add(MaxPooling2D(pool_size=(2,2)))

/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:2: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (3, 3), activation="relu")`
  


In [180]:
    
Classifier.add(Flatten())

In [181]:
Classifier.add(Dense(128, activation ='relu'))

In [182]:
Classifier.add(Dense(128, activation ='relu'))

In [183]:
Classifier.add(Dense(128, activation ='relu'))

In [184]:
Classifier.add(Dense(output_dim =1 , activation='sigmoid'))

/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1)`
  """Entry point for launching an IPython kernel.


In [185]:
Classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [188]:


# Part 2 - Fitting the CNN to the images
import tensorflow as TF 
from keras.preprocessing.image import ImageDataGenerator


# we dont change anything on the below , just copy and paste from keras doc
# we create object train_datagen to use for other part

train_datagen = ImageDataGenerator(
        rescale=1./255,
        shear_range=0.2,
        zoom_range=0.2,
        horizontal_flip=True)

# another datagen object for test to apply on test set

test_datagen = ImageDataGenerator(rescale=1./255)

# we change name and directory
# also target size should the same 1st step on convo;ution2d

# batch size is 32 

# class mode is okay as we only have 2 category 0/1 for output

training_set = train_datagen.flow_from_directory(
        'Data/Train',
        target_size=(64,64), # target size is the dim on CNN model on convultion2d which 64,64
        batch_size=5,
        class_mode='binary')



# now test data
# we change the direcotry and traget size

test_set = test_datagen.flow_from_directory(
        'Data/Test',
        target_size=(64, 64), # becasue input for convultion is 64
        batch_size=4,
        class_mode='binary')


# now fitting model 

# sample is 8000 as we have 4000 for dog and 4000 for cat

# number of epoch for training 50 is high we can choose 25 for iteration

Classifier.fit_generator(
        training_set,
        steps_per_epoch=135,
        epochs=25,
        validation_data=test_set,
        validation_steps=19)  # number of images in test _set which is 2000 1k for cat and 1 k for dog

Found 117 images belonging to 2 classes.
Found 19 images belonging to 2 classes.
Epoch 1/25
135/135 [==============================] - 98s 727ms/step - loss: 7.8892e-04 - acc: 1.0000 - val_loss: 1.2440 - val_acc: 0.8356
Epoch 2/25
135/135 [==============================] - 97s 717ms/step - loss: 0.0191 - acc: 0.9926 - val_loss: 1.0006 - val_acc: 0.8611
Epoch 3/25
135/135 [==============================] - 96s 712ms/step - loss: 0.0490 - acc: 0.9911 - val_loss: 1.8485 - val_acc: 0.8333
Epoch 4/25
135/135 [==============================] - 95s 705ms/step - loss: 0.0601 - acc: 0.9800 - val_loss: 1.7884 - val_acc: 0.8194
Epoch 5/25
135/135 [==============================] - 91s 677ms/step - loss: 0.0200 - acc: 0.9926 - val_loss: 1.2896 - val_acc: 0.9028
Epoch 6/25
135/135 [==============================] - 88s 655ms/step - loss: 0.0023 - acc: 1.0000 - val_loss: 1.6552 - val_acc: 0.8904
Epoch 7/25
135/135 [==============================] - 89s 660ms/step - loss: 0.0020 - acc: 1.0000 - val_l

In [200]:
Classifier.save_weights('AziCNN.hdf5' )

In [201]:
Classifier.load_weights('AziCNN.hdf5')

In [202]:
# to test the model  


import numpy as np

from keras.preprocessing import image
test_image=image.load_img( 'Data/Image.jpeg',
                         target_size=(64,64))  #based model convolutional  



# convert image to array

test_image=image.img_to_array(test_image)


# we get error if we put it on classifer it need one more dimension
#  Classifier.predict(test_image)


# so we add one more dimension


test_image=np.expand_dims(test_image,axis=0)

Classifier.predict(test_image)

# this gives us 0 or 1 to inderstand

# use below

training_set.class_indices

{'Azadeh': 0, 'Iman': 1}

In [203]:
Classifier.predict(test_image)


array([[1.]], dtype=float32)

In [204]:
import numpy as np

from keras.preprocessing import image
test_image=image.load_img( 'Data/I2.jpg',
                         target_size=(64,64))  #based model convolutional  



# convert image to array

test_image=image.img_to_array(test_image)


# we get error if we put it on classifer it need one more dimension
#  Classifier.predict(test_image)


# so we add one more dimension


test_image=np.expand_dims(test_image,axis=0)

Classifier.predict(test_image)

array([[1.]], dtype=float32)

In [206]:
import numpy as np

from keras.preprocessing import image
test_image=image.load_img( 'Data/ii.jpg',
                         target_size=(64,64))  #based model convolutional  



# convert image to array

test_image=image.img_to_array(test_image)


# we get error if we put it on classifer it need one more dimension
#  Classifier.predict(test_image)


# so we add one more dimension


test_image=np.expand_dims(test_image,axis=0)

Classifier.predict(test_image)


array([[0.00186344]], dtype=float32)